name: gt_secure
description: "A production-ready Flutter package for secure local storage with AES-256-CBC encryption, automatic key management, in-memory caching, and comprehensive error handling. Perfect for storing sensitive data like authentication tokens, user credentials, and encrypted preferences."
version: 1.0.0
homepage: https://github.com/GauravTechnical24/gt_secure.git
repository: https://github.com/GauravTechnical24/gt_secure.git
issue_tracker: https://github.com/GauravTechnical24/gt_secure/issues

topics:
  - secure-storage
  - encryption
  - security
  - storage
  - flutter

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  encrypt: ^5.0.3
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
